import { TranscriptionProvider, TranscriptionResponse } from '../types';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';

const execAsync = promisify(exec);

export class LocalWhisperProvider implements TranscriptionProvider {
  name = 'local' as const;

  async transcribe(file: File | Blob | Buffer, fileName: string = 'audio.mp3'): Promise<TranscriptionResponse> {
    const tempDir = os.tmpdir();
    // Unique name to avoid collisions
    const safeName = `${Date.now()}-${Math.random().toString(36).substring(7)}-${fileName.replace(/[^a-z0-9.]/gi, '_')}`;
    const filePath = path.join(tempDir, safeName);

    try {
      // Write Buffer to temp file
      let buffer: Buffer;
      if (Buffer.isBuffer(file)) {
        buffer = file;
      } else if (file instanceof Blob || file instanceof File) {
        buffer = Buffer.from(await file.arrayBuffer());
      } else {
        throw new Error('Invalid file type for local Whisper transcription');
      }

      await fs.writeFile(filePath, buffer);

      // Run `whisper` CLI (must be installed globally via pip)
      // whisper /path/to/file.mp3 --model base --output_format txt --output_dir /path/to/tempdir
      // We assume Python's whisper CLI is available in PATH.
      const cmd = `whisper "${filePath}" --model base --output_format txt --output_dir "${tempDir}"`;
      
      const { stdout, stderr } = await execAsync(cmd);
      
      // Look for the output txt file generated by whisper
      // It names it identically to input with .txt extension
      const basename = path.basename(filePath, path.extname(filePath));
      const txtPath = path.join(tempDir, `${basename}.txt`);

      let transcript = '';
      try {
        transcript = await fs.readFile(txtPath, 'utf8');
      } catch (err: any) {
        console.error('[LocalWhisperProvider] Warning: Generated TXT file not found, extracting from stdout if possible.', err.message);
        throw new Error('Local whisper process failed to generate transcript text file.');
      }

      // Cleanup
      await fs.rm(filePath, { force: true });
      await fs.rm(txtPath, { force: true }).catch(() => {});
      
      return {
        success: true,
        provider: this.name,
        transcript: transcript.trim(),
      };
    } catch (error: any) {
      console.error('[LocalWhisperProvider Error]:', error.message);
      
      // Cleanup on failure
      await fs.rm(filePath, { force: true }).catch(() => {});

      return {
        success: false,
        provider: this.name,
        transcript: '',
        error: error.message || 'Unknown Local Whisper Error',
      };
    }
  }
}
